### ISSUE TITLE
Unable to find a way to remove some metadata from the .po file

### ISSUE THREAD

**Issue by intiocean** [mondeja/pre-commit-po-hooks#21]
I would like to remove some un-needed metadata from the .po file that just makes diffs longer and conflicts more likely when various branches touch a .po file.

The pre-commit config I tried in order to remove the `POT-Creation-Date` metadata. (I'm also happy to leave it in and just set it to a blank or fixed date).

```
  - repo: https://github.com/mondeja/pre-commit-po-hooks
    rev: v1.7.3
    hooks:
      - id: check-metadata
        args: ["--header=POT-Creation-Date", "value=''"]
```

But I get the following error 
```
check-metadata...........................................................Failed
- hook id: check-metadata
- exit code: 2

usage: check-po-metadata-hook
       [-h]
       [-n]
       [-r]
       [-s]
       [-q]
       [filenames ...]
check-po-metadata-hook: error: unrecognized arguments: --header=POT-Creation-Date
```

I've had a play around and can't identify the issue. Is this something I should be able to do with this hook?
